/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.panier;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;

/**
 *
 * @author vb394093
 */
public class VueGAWT extends java.awt.Frame implements VueGraphique {

    /**
     * Creates new form VueGAWT
     */
    public VueGAWT() {
        initComponents();
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e)
            {
                System.exit(0);
            }
        });
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setName("Panier"); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 200));
        setTitle("Panier");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        add(jLabel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("+");
        add(jButton1, java.awt.BorderLayout.NORTH);

        jButton2.setText("-");
        add(jButton2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGAWT().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void addControleur(MControler c)
    {
        jButton1.addActionListener(c);
        jButton2.addActionListener(c);
    }
    
    public JButton getBtn1(){
        return jButton1;
    }
    public JButton getBtn2(){
        return jButton2;
    }
    
    @Override
    public void update(Observable o, Object arg) {
        jLabel1.setText(Integer.toString(((Panier)o).quantite()));
    }
}

